---
title: "basket-EDA"
output: 
  html_document:
    toc: yes
    toc_depth: '3'
    df_print: paged
  pdf_document:
    toc: yes
    toc_depth: 3
date: "2023-01-29"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r  echo=TRUE}
data <- read.csv("/home/noemi/Scrivania/Basketball_Data_futuro.csv")

head(data)
str(data)
summary(data)

k=0
c = seq(0, 47)
for(i in 1:nrow(data)){
  if(data[i,"PTS_away"]==0){
     k=k+1
    c[k]= i
  }
}

c
k


data <- data[-c(17877, 17884, 17902,19136,19137, 19138, 19141, 19142, 19143, 19144, 19145, 19146, 19150, 19152, 19153, 19154, 19155, 19156, 19157, 19158,19159,19160, 19161, 19162, 19163, 19164, 19165, 19166, 19167, 19168, 19169, 19170, 19171, 19172, 19173, 19174, 19175, 19176, 19177, 19178, 19179,19180, 19181, 19182, 19183, 19184, 19185, 19186, 19187, 19188, 19189, 19190), ]


str(data)
summary(data)



G <- data

G[, 8] <- (G[, 8]-G[, 14])
G[, 9] <-(G[, 9]-G[, 15])
G[, 10] <-(G[, 10]-G[, 16])
G[, 11] <-(G[, 11]-G[, 17])
G[, 12] <-(G[, 12]-G[, 18])
G[, 20] <-(G[, 20]-G[, 23])
G[, 21] <-(G[, 21]-G[, 24])
G[, 22] <-(G[, 22]-G[, 25])
G[, 26] <- (G[, 26] - G[, 27]) 
G[, 28] <-(G[, 28] - G[, 29]) 
G[, 30] <-(G[, 30] - G[, 31]) 
G[, 32] <-(G[, 32] - G[, 33]) 

G2 <- G[, -c(1,2,3,4,5,6,7,13,14,15,16,17,18,23,24,25,27,29,31,32,33)]


colnames(G2) <- substring(colnames(G2), 1,nchar(colnames(G2))-5)

colnames(G2)[6] <- "HOME_TEAM_WINS"
head(G2)
str(G2)


cor_matrix <- cor(G2)
library(corrplot)
corrplot(cor_matrix, method="number")

data$HOME_TEAM_WINS <- as.factor(data$HOME_TEAM_WINS)
G2$HOME_TEAM_WINS <- as.factor(G2$HOME_TEAM_WINS)





library(rpart)
library(rpart.plot)
library(dplyr)
library(glue)
library(ggplot2)
library(randomForest)
library(pROC)
library(caret)
library(readr)


set.seed(123)

#--------------------------------------------------------------------------
# Training and Test set
#--------------------------------------------------------------------------
train <- sample(1:nrow(G2), as.integer(nrow(G2)*0.8))
data.train <- G2[train,]
data.test <- G2[-train,]
summary(data.train$HOME_TEAM_WINS)
summary(data.test$HOME_TEAM_WINS)
winning.test <- G2$HOME_TEAM_WINS[-train]

head(G2[train,])
str(G2[train,])

#--------------------------------------------------------------------------
# Tree
#--------------------------------------------------------------------------

# Define the response variable
response_var <- "HOME_TEAM_WINS"

# Define the predictor variables
predictor_vars <- setdiff(colnames(G2), response_var)

# Build the decision tree
dt <- rpart(as.formula(paste(response_var, "~", paste(predictor_vars, collapse = "+"))), data = G2[train,], method = "class")

# Plot the tree
plot(dt)
text(dt)

# predict the values for the test sample
pred <- predict(dt, data.test, type = "class")

# evaluate the model performance
table(pred, winning.test)

confusionMatrix(pred, winning.test,positive = "1", dnn = c("Prediction", "Reference"))


#-------------------------------------------------------------------------
# ROC curve of Tree with imbalanced data
#-------------------------------------------------------------------------
pred1 <- predict(dt, data.test, type = "prob")

par(pty = "s")
roc(data.test$HOME_TEAM_WINS, pred1[,1], plot=TRUE, legacy.axes = TRUE, xlab = "False Positive Rate", ylab = "True Positive Rate", col = "#377eb8", lwd = 4, print.auc = TRUE)


#-------------------------------------------------------------------------
#Bagging
#--------------------------------------------------------------------------
bag <- randomForest(HOME_TEAM_WINS ~ ., data = data.train, mtry = 2)
pred <- predict(bag, data.test, type = "class")

importance(bag)

confusionMatrix(pred, data.test$HOME_TEAM_WINS, positive = "1")


#-------------------------------------------------------------------------
# ROC curve of Bagging with imbalanced data
#-------------------------------------------------------------------------
pred1 <- predict(bag, data.test, type = "prob")

par(pty = "s")
roc(data.test$HOME_TEAM_WINS, pred1[,1], plot=TRUE, legacy.axes = TRUE, xlab = "False Positive Rate", ylab = "True Positive Rate", col = "#377eb8", lwd = 4, print.auc = TRUE)




#-------------------------------------------------------------------------
#Random Forest with imbalanced data
#-------------------------------------------------------------------------



(rf_fit <- randomForest(HOME_TEAM_WINS ~ ., data = data.train, ntree=500))
plot(rf_fit)
importance(rf_fit)
pred <- predict(rf_fit, data.test)
confusionMatrix(pred, data.test$HOME_TEAM_WINS, positive = "1", dnn = c("Prediction", "Reference"))

#-------------------------------------------------------------------------
# ROC curve of Random Forest with balanced data
#-------------------------------------------------------------------------
pred1 <- predict(rf_fit, data.test, type = "prob")

par(pty = "s")
roc(data.test$HOME_TEAM_WINS, pred1[,1], plot=TRUE, legacy.axes = TRUE, xlab = "False Positive Rate", ylab = "True Positive Rate", col = "#377eb8", lwd = 4, print.auc = TRUE)






library(carData)
write.csv(G2, file = "Basket_data_analisi.csv", row.names = FALSE)






```






```
